default: &default
  ahn_core_username: "rayo@somleng.org"
  ahn_core_password: "secret"

production:
  <<: *default
  sentry_dsn: "<%= AppSettings.credentials.fetch(:sentry_dsn) %>"
  ahn_core_password: "<%= AppSettings.credentials.fetch(:ahn_core_password) %>"

development: &development
  <<: *default

test:
  <<: *development
